### ISSUE TITLE
can't add package

### ISSUE THREAD

**Issue by laurentopia** [pschraut/UnityTexture3DAtlasImportPipeline#1]
Cannot perform upm operation: Unable to add package [https://github.com/pschraut/UnityTexture3DAtlasImportPipeline.git#1.1.0 ]:
  Cannot checkout repository [https://github.com/pschraut/UnityTexture3DAtlasImportPipeline.git]:
    Error when executing git command. error: pathspec '1.1.0 ' did not match any file(s) known to git
 [NotFound].See console for more details
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by pschraut** [comment]
The package URL you used is wrong. You don't want the space at the end `#1.1.0 ]`

**Comment by shirleycreates12** [comment]
> The package URL you used is wrong. You don't want the space at the end `#1.1.0 ]`

I've been tyring at a similar issue for hours, of course, it would be something simple like this LOL! Thanks for clarifying
